project:
  type: website

website:
  title: "Regional Datahub"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: StateOfTheRegion.qmd
        text: State Of The Region
        
      - href: business.qmd
        text: Business Indicators

format:
  html:
    theme: cosmo