---
title: "Regional Datahub"
format:
  html:
    theme: cosmo
    toc: false
---

## 

The Upjohn Regional team provides up-to-date, downloadable measures of labor market and economic development conditions for every county in Michigan. These metrics are designed to support a wide range of users, including county governments, small businesses, nonprofits, companies considering relocation or expansion, local and state policymakers, public engagement advocates, and civic organizations.

The Upjohn Regional Data Hub is organized into four sections: Workforce, Business, Housing and Transportation, and Demographics and Equity Indicators. Most data are available at the county level, and users can select Michigan counties using the dropdown menus, with Southwest Michigan counties listed first. Beneath each graph, an additional dropdown provides the indicator definition, data source and data download.

Please [contact us](mailto:regional@upjohn.org) if you have any questions. 

Visit [Upjohn Regional](https://www.upjohn.org/division/upjohn-regional) for more information.

## 

## View and download the most current data

::: {.grid}

::: {.g-col-6}
[Workforce](StateOfTheRegion.qmd){.btn .home-button .btn-lg .w-100}
:::

::: {.g-col-6}
[Business](business.qmd){.btn .home-button .btn-lg .w-100}
:::

::: {.g-col-6}
[Housing and Transportation](workforce.qmd){.btn .home-button .btn-lg .w-100}
:::

::: {.g-col-6}
[Demographics and Equity](equity.qmd){.btn .home-button .btn-lg .w-100}
:::

:::
