---
title: "State Of The Region"
editor: visual
format:
  html:
    theme: cosmo
---

```{r}
#| label: EPOP
#| echo: false
#| message: false
#| warning: false

library(dplyr)
library(plotly)

labor <- readRDS("data/EPOP_LFPR_UR.rds")

all_counties <- unique(labor$county)

init <- all_counties[1]

df_init <- labor %>%
  filter(county == init)

p <- plot_ly()

# County epop 
p <- p %>%
  add_lines(
    data = df_init,
    x = ~period_date,
    y = ~EPOP,
    name = init,
    line = list(width = 3),
    customdata = ~period_txt,
    hovertemplate = paste(
      "%{x}<br>",
      "Value: %{y:.2f}%<br>",
      "Period: %{customdata}<extra></extra>"
    )
  )

# Michigan unemployment rate
p <- p %>%
  add_lines(
    data = df_init,
    x = ~period_date,
    y = ~MI_employment_population_ratio,
    name = "Michigan",
    line = list(width = 3, dash = "dash"),
    customdata = ~period_txt,
    hovertemplate = paste(
      "%{x}<br>",
      "Value: %{y:.2f}%<br>",
      "Period: %{customdata}<extra></extra>"
    )
  )

buttons <- lapply(seq_along(all_counties), function(i) {

  df <- labor %>%
    filter(county == all_counties[i])

  list(
    method = "restyle",
    args = list(
      list(
        x = list(df$period_date, df$period_date),
        y = list(
          df$EPOP,
          df$MI_employment_population_ratio
        ),
        name = list(
          all_counties[i],
          "Michigan"
        )
      ),
      c(0,1)
    ),
    label = all_counties[i]
  )
})

p %>%
  layout(
    annotations = list(
      list(
        text = "<b>Source:</b> U.S. Bureau of Economic Analysis (BEA), FRED",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.35,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      ),
      list(
        text = "Not Seasonally Adjusted.Preliminary data (p) and estimates (e) are noted in the text box.",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.45,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      )
    ),

    title = paste(
      "Employment to Population Ratio:",
      init,
      "vs Michigan"
    ),

    xaxis = list(
      title = "Period"),

    yaxis = list(title = "Percent"),

    updatemenus = list(
      list(
        buttons = buttons,
        x = 1.25,
        y = 0.75,
        xanchor = "right"
      )
    ),

    margin = list(
      t = 30,
      b = 180
    )
  ) %>%
  config(displayModeBar = FALSE)

```

```{r}
#| label: LFPR
#| echo: false
#| message: false
#| warning: false

library(dplyr)
library(plotly)

labor <- readRDS("data/EPOP_LFPR_UR.rds")

all_counties <- unique(labor$county)

init <- all_counties[1]

df_init <- labor %>%
  filter(county == init)

p <- plot_ly()

# County epop 
p <- p %>%
  add_lines(
    data = df_init,
    x = ~period_date,
    y = ~LFPR,
    name = init,
    line = list(width = 3),
    customdata = ~period_txt,
    hovertemplate = paste(
      "%{x}<br>",
      "Value: %{y:.2f}%<br>",
      "Period: %{customdata}<extra></extra>"
    )
  )

# Michigan unemployment rate
p <- p %>%
  add_lines(
    data = df_init,
    x = ~period_date,
    y = ~MI_labor_force_participation_rate,
    name = "Michigan",
    line = list(width = 3, dash = "dash"),
    customdata = ~period_txt,
    hovertemplate = paste(
      "%{x}<br>",
      "Value: %{y:.2f}%<br>",
      "Period: %{customdata}<extra></extra>"
    )
  )

buttons <- lapply(seq_along(all_counties), function(i) {

  df <- labor %>%
    filter(county == all_counties[i])

  list(
    method = "restyle",
    args = list(
      list(
        x = list(df$period_date, df$period_date),
        y = list(
          df$LFPR,
          df$MI_labor_force_participation_rate
        ),
        name = list(
          all_counties[i],
          "Michigan"
        )
      ),
      c(0,1)
    ),
    label = all_counties[i]
  )
})

p %>%
  layout(
    annotations = list(
      list(
        text = "<b>Source:</b> U.S. Bureau of Economic Analysis (BEA), FRED",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.35,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      ),
      list(
        text = "Not Seasonally Adjusted.Preliminary data (p) and estimates (e) are noted in the text box.",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.45,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      )
    ),

    title = paste(
      "Labor Force Participation Rate:",
      init,
      "vs Michigan"
    ),

    xaxis = list(
      title = "Period"),

    yaxis = list(title = "Percent"),

    updatemenus = list(
      list(
        buttons = buttons,
        x = 1.25,
        y = 0.75,
        xanchor = "right"
      )
    ),

    margin = list(
      t = 30,
      b = 180
    )
  ) %>%
  config(displayModeBar = FALSE)

```

```{r}
#| label: UR
#| echo: false
#| message: false
#| warning: false

library(dplyr)
library(plotly)

labor <- readRDS("data/EPOP_LFPR_UR.rds")

all_counties <- unique(labor$county)

init <- all_counties[1]

df_init <- labor %>%
  filter(county == init)

p <- plot_ly()

# County unemployment rate
p <- p %>%
  add_lines(
    data = df_init,
    x = ~period_date,
    y = ~unemployment_rate,
    name = init,
    line = list(width = 3),
    customdata = ~period_txt,
    hovertemplate = paste(
      "%{x}<br>",
      "Value: %{y:.2f}%<br>",
      "Period: %{customdata}<extra></extra>"
    )
  )

# Michigan unemployment rate
p <- p %>%
  add_lines(
    data = df_init,
    x = ~period_date,
    y = ~MI_unemployment_rate,
    name = "Michigan",
    line = list(width = 3, dash = "dash"),
    customdata = ~period_txt,
    hovertemplate = paste(
      "%{x}<br>",
      "Value: %{y:.2f}%<br>",
      "Period: %{customdata}<extra></extra>"
    )
  )

buttons <- lapply(seq_along(all_counties), function(i) {

  df <- labor %>%
    filter(county == all_counties[i])

  list(
    method = "restyle",
    args = list(
      list(
        x = list(df$period_date, df$period_date),
        y = list(
          df$unemployment_rate,
          df$MI_unemployment_rate
        ),
        name = list(
          all_counties[i],
          "Michigan"
        )
      ),
      c(0,1)
    ),
    label = all_counties[i]
  )
})

p %>%
  layout(
    annotations = list(
      list(
        text = "<b>Source:</b> U.S. Bureau of Economic Analysis (BEA), FRED",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.35,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      ),
      list(
        text = "Not Seasonally Adjusted.Preliminary data (p) and estimates (e) are noted in the text box.",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.45,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      )
    ),

    title = paste(
      "Unemployment Rate:",
      init,
      "vs Michigan"
    ),

    xaxis = list(
      title = "Period"),

    yaxis = list(title = "Percent"),

    updatemenus = list(
      list(
        buttons = buttons,
        x = 1.25,
        y = 0.75,
        xanchor = "right"
      )
    ),

    margin = list(
      t = 30,
      b = 180
    )
  ) %>%
  config(displayModeBar = FALSE)
```

```{r}
#| label: AWW
#| echo: false
#| message: false
#| warning: false

library(plotly)
library(dplyr)

qcew_data <- readRDS("data/qcew.rds")

# Ensure proper ordering
qcew_data <- qcew_data %>%
  arrange(year, quarter)

# Get counties
counties <- unique(qcew_data$county)

# Default county
default_county <- "Kalamazoo"

# Initial dataset
initial_data <- qcew_data %>%
  filter(county == default_county)

# Create plot
fig <- plot_ly()

# County bars
fig <- fig %>%
  add_trace(
    data = initial_data,
    x = ~date,
    y = ~avg_wkly_wage,
    type = "bar",
    name = default_county
  )

# State line
fig <- fig %>%
  add_trace(
    data = initial_data,
    x = ~date,
    y = ~state_avg_wkly_wage,
    type = "scatter",
    mode = "lines",
    name = "Michigan Average",
    line = list(
      dash = "dash"
    )
  )

# Dropdown buttons
buttons <- lapply(seq_along(counties), function(i) {

  county_name <- counties[i]

  county_data <- qcew_data %>%
    filter(county == county_name)

  list(
    method = "update",
    args = list(
      list(
        y = list(
          county_data$avg_wkly_wage,
          county_data$state_avg_wkly_wage
        ),
        x = list(
          county_data$date,
          county_data$date
        )
      ),
      list(
        title = paste(
          "Average Weekly Wage:",
          county_name,
          "County vs Michigan"
        )
      )
    ),
    label = county_name
  )
})

# Layout
fig <- fig %>%
  layout(
    title = paste(
      "Average Weekly Wage:",
      default_county,
      "County vs Michigan"
    ),
    
    updatemenus = list(
      list(
        active = which(counties == default_county) - 1,
        buttons = buttons,
        x = 1.25,
        y = .75,
        xanchor = "right"
      )
    ),
    
    annotations = list(
      list(
        text = "<b>Source</b>: U.S. Bureau of Economic Analysis (BEA), FRED",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.35,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      ),
       list(
        text = "Not Seasonally Adjusted.",
        xref = "paper",
        yref = "paper",
        x = 0,
        y = -0.45,
        showarrow = FALSE,
        xanchor = "left",
        font = list(size = 10)
      )
      
    ),
    
    margin = list(
      t = 30,
      b = 160
    ),
    
    xaxis = list(title = "Date"),
    
    yaxis = list(
      title = "Average Weekly Wage ($)"
    ),
    
    barmode = "group"
  )

config(fig,
       displayModeBar = FALSE)

```
